apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-order-service
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: mes-order-service
      type: service
      env: prod
  template:
    metadata:
      labels:
        app: mes-order-service
        type: service
        env: prod
    spec:
      containers:
        - name: mes-order-service
          image: mes-order-service:latest  # Docker image
          ports:
            - containerPort: 8080